### ISSUE TITLE
Test local in k8s

### ISSUE THREAD

**Issue by rkATmsk** [open-metadata/openmetadata-helm-charts#129]
Hi Team,

I am trying to install the Ingestion in local, but its failed to create a PVC with ReadWriteMany.

Also the validation fail to keep ReadWriteOnce.

Any help to run local ? may be i need to disable the template validation ? 
```
Events:
  Type     Reason                Age                   From                                                                                                Message
  ----     ------                ----                  ----                                                                                                -------
  Normal   WaitForFirstConsumer  41m                   persistentvolume-controller                                                                         waiting for first consumer to be created before binding
  Normal   Provisioning          10m (x8 over 41m)     rancher.io/local-path_local-path-provisioner-684f458cdd-vztxn_237b9e7f-993b-49b4-938b-2731994ad6e0  External provisioner is provisioning volume for claim "default/openmetadata-dependencies-logs"
  Warning  ProvisioningFailed    10m (x8 over 41m)     rancher.io/local-path_local-path-provisioner-684f458cdd-vztxn_237b9e7f-993b-49b4-938b-2731994ad6e0  failed to provision volume with StorageClass "standard": Only support ReadWriteOnce access mode
  Normal   ExternalProvisioning  114s (x162 over 41m)  persistentvolume-controller                                                                         waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
```

`Error: INSTALLATION FAILED: execution error at (openmetadata-dependencies/charts/airflow/templates/_helpers/validate-values.tpl:105:5): The `logs.persistence.accessMode` must be `ReadWriteMany`!`

**Comment by rkATmsk** [comment]
```
###
### Refer default  vaules in https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/deps/values.yaml
mysql:
  primary:
    persistence:
      size: 20Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256M"
      limits:
        cpu: "1000m"
        memory: "1024M"

elasticsearch:
  resources:
    requests:
      cpu: "100m"
      memory: "256M"
    limits:
      cpu: "1000m"
      memory: "1024M"

airflow:
  enabled: true
  dags:
    persistence:
      enabled: false
  logs:
    persistence:
      enabled: false
```

This works for local without persisting the data
