### ISSUE TITLE
Support ElasticSearch username and password

### ISSUE THREAD

**Issue by lihan** [open-metadata/openmetadata-helm-charts#14]
We need to use Elastic.co for production deployment, the default configuration comes with a password, so it should be configurable.

My walk around

```
  extraEnvs:
    - name: ELASTICSEARCH_USERNAME
      value: elastic
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "es-secrets"
          key: "es-password"
```
