### ISSUE TITLE
Add namespace to helm template result

### ISSUE THREAD

**Issue by danielcarletti** [open-metadata/openmetadata-helm-charts#141]
When we helm template the main chart, it does not add namespace to the manifest. Would be great to have this, otherwise you would need to always do a helm install.

To replicate:
```
helm repo add open-metadata https://helm.open-metadata.org/
helm repo update
helm template openmetadata open-metadata/openmetadata --namespace my_namespace
```

Expected:
Manifest is filled with namespaces. Ex.:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata
  namespace: my_namespace
  labels:
    helm.sh/chart: openmetadata-1.0.1
    app.kubernetes.io/name: openmetadata
    app.kubernetes.io/instance: openmetadata
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
...
```
