### ISSUE TITLE
Add randomized fernet key instead of hardcoded values in template for potential security risk

### ISSUE THREAD

**Issue by davionchai** [open-metadata/openmetadata-helm-charts#147]
Instead of hardcoding fernet key in the values file
```
  fernetkey:
    value: "jJ/9sz0g0OHxsfxOoSfdFdmk3ysNmPRnH3TUAbz3IHA="
    secretRef: ""
    secretKey: ""
```
a safer way is to use `(randAlphaNum 32 | b64enc)` as part of the initialization if  `fernetKey.secretRef: ~`

I am curious if the hardcoded value is indeed intended

with that, it is also easier if we move `fernetKey.secretRef` and `fernetKey.secretKey` to `.tpl` and format its naming with `{{ .Release.Name }}` which i think would be another scope to discuss with
