### ISSUE TITLE
Missing volume mounts in init-containers

### ISSUE THREAD

**Issue by cristiancalugaru** [open-metadata/openmetadata-helm-charts#173]
Upgrading a K8s OM deployment from helm chart 1.0.6 to 1.1.5 throws an error on the run-db-migrations container, with
failed with :
 `ElasticsearchException[Failed to create elastic search client ]; nested: RuntimeException[Failed to create SSLContext for [ElasticSearch]]; nested: NoSuchFileException[/truststore/truststore.jks];`

Reproduce-able setup:

A trust store for elastic search, with a mount volume and a config map:

```
extraVolumeMounts:
  - name: es-truststore
    mountPath: /truststore
extraVolumes:
  - name: es-truststore
    configMap:
      name: es-metadata-dev-truststore
      items:
      - key: truststore.jks
        path: truststore.jks
```

Describing the init container pod, there is no `/truststore` path mounted.
`kubectl describe pod openmetadata-797487cbb7-2htcd`

```
Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xsjjh (ro)
```
`/truststore` volume is not mounted.
