### ISSUE TITLE
env value string should be quoted

### ISSUE THREAD

**Issue by advincze** [open-metadata/openmetadata-helm-charts#19]
in v0.0.7
helm gives me an error:

```
UPGRADE FAILED: pre-upgrade hooks failed: warning: Hook pre-upgrade openmetadata/templates/check-db-migrations-job-hook.yaml failed: Job in version "v1" cannot be handled as a Job: v1.Job.Spec: v1.JobSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 8, error found in #10 byte of ...|,"value":8585},{"nam|..., bigger context ...|e":"openmetadata"},{"name":"SERVER_PORT","value":8585},{"name":"SERVER_ADMIN_PORT","value":8586},{"n|..
```

e.g. the deployment.yaml rendered looks like this: 
```yaml
...
containers:
        - name: openmetadata
   ...
          env:
          - name: SERVER_HOST
            value: openmetadata
          - name: SERVER_PORT
            value: 8585  #<--- this is not allowed because string type is expected, but for yaml it is not a string but a number
          - name: SERVER_ADMIN_PORT
            value: 8586
          - name: ELASTICSEARCH_HOST
            value: elasticsearch-master.openmetadata.svc.cluster.local
          - name: ELASTICSEARCH_PORT
            value: 9200
          - name: ELASTICSEARCH_SCHEME
            value: http
          - name: MYSQL_HOST
            value: mysql.openmetadata.svc.cluster.local
          - name: MYSQL_PORT
            value: 3306
```
e.g. here
https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/openmetadata/templates/deployment.yaml#L71
