### ISSUE TITLE
SalesForce Connector SSL issue, on ingestor 

### ISSUE THREAD

**Issue by elguero6** [open-metadata/openmetadata-helm-charts#203]
I'm in a kubernetes environment, I'm trying to specify the ca-bundle.crt, in the ingestion POD for a Salesforce database service. Airflow spins up a pod when the ingestion is run/scheduled.  I'm able to connect to Salesforce Successfully when I test the connection on the openmetadata UI. Heres is my values.yaml for the openmetadata-dependencies  

```
mysql:
  primary:
    `resources:`
      limits:
        memory: 1024Mi
        cpu: 1000m
      requests:
        memory: 512Mi
        cpu: 500m
    startupProbe:
      initialDelaySeconds: 200
airflow:
  airflow:
    config:
      PYTHONHTTPSVERIFY: 0
      AIRFLOW_VERIFY_SSL: ignore
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      DEFAULT_CA_BUNDLE_PATH: /etc/ssl/certs/ca-certificates.crt
      _CACERT_PATH: /etc/ssl/certs/ca-certificates.crt
  web:
    extraVolumes:
    - name: openmetadata-cacerts
      hostPath:
        path: /Users/test/openmetadata/certs/java-cert/cacerts
        type: File
    - name: openmetadata-crt
      hostPath:
        path: /Users/test/git/openmetadata/ca-bundle.crt
        type: File
    extraVolumeMounts:
    - name: openmetadata-cacerts
      mountPath: "/usr/lib/jvm/default-jvm/lib/security/cacerts"
    - name: openmetadata-crt
      mountPath: "/etc/ssl/certs/ca-certificates.crt"

```
**Steps to reproduce** 

1.) Create Salesforce DatabaseConnection 
2.) Create and Deploy ingestion
3.) Run Ingestion

[2023-12-12T20:44:52.871+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
