### ISSUE TITLE
Add external elasticsearch

### ISSUE THREAD

**Issue by dkkaygorodov** [open-metadata/openmetadata-helm-charts#215]
### Checks

- [X] I have checked for existing issues.
- [X] This request is about the Openmetadata Helm Chart.
- [x] This request is about the Openmetadata Dependencies Helm Chart.

### Description

HI
I use external elasticsearch installation with self-signed certificates (not like helm dependence, or k8s installation)
And I can't connect to my elasticsearch stack, because I can't add certs in openmetadata chart (no option, maybe have another reason?)
When you add this feature?

### Proposed Implementation

Maybe you can add something like that:
```
elasticsearch:
      host: external-host-ip
      port: someport
      scheme: http
      ...
      cert: path/to/cert/in/container-openmetadata.crt
      key: path/to/cert/in/container.crt
```
or
```
elasticsearch:
      host: external-host-ip
      port: someport
      scheme: http
      ...
      useSelfSignSerts:
        enabled: true
        cert:
          secretRef: openmetadata
          secretKey: elastic-cert
        key:
          secretRef: openmetadata
          secretKey: elastic-key

```

### Have you joined Openmetadata Slack community?

No
