### ISSUE TITLE
Unable to bootstrap admin with password on startup 

### ISSUE THREAD

**Issue by ffais** [open-metadata/openmetadata-helm-charts#218]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [X] This report is about the Openmetadata Dependencies Helm Chart.

### Description

I'm trying to bootstrap admins with custom password on server startup. I'm setting the values _openmetadata.config.authorizer.initialAdmins_ to admin:test12345 as mentioned in the [documentation](https://docs.open-metadata.org/v1.3.x/deployment/security/basic-auth#authorizer-configuration).  By adding this configuration both the credentials I configured and the default 'admin/admin' are not accepted.

### Steps to reproduce

Install openmetadata setting the password in the initialAdmins value.

### Chart Version

1.3.0

### App Version

1.3.0

### Kubernetes Version

v1.28.5

### Helm Version

v3.14.0

### Relevant Logs

```shell
This is the query on the openmetadata database:

select name from public.user_entity;
             name             
------------------------------
 admin:test12345
 DataInsightsApplicationBot
 ingestion-bot
 SearchIndexingApplicationBot
```
```


### Custom Helm Values

```yaml
openmetadata:
  enabled: true
  nameOverride: openmetadata
  fullnameOverride: "openmetadata"
  openmetadata:
    config:
      authorizer:       
        initialAdmins:
          - "admin:test12345"
      database:
        enabled: true
        host: openmetadata-postgres-cluster
        port: 5432
        driverClass: org.postgresql.Driver
        databaseName: openmetadata
        dbScheme: postgresql
        dbParams: "&ssl=true&sslmode=require"
        auth:
          username: openmetadata
          password:
            secretRef: openmetadata.openmetadata-postgres-cluster.credentials.postgresql.acid.zalan.do
            secretKey: password
      pipelineServiceClientConfig:
        auth:
          enabled: true
          username: digitalhub
          password:
            secretRef: airflow-admin-password
            secretKey: password
```

### Have you joined Openmetadata Slack community?

No
