### ISSUE TITLE
Azure Secrets Manager not supported by the chart

### ISSUE THREAD

**Issue by Nemeczek** [open-metadata/openmetadata-helm-charts#222]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

I am trying to follow guide to add secrets manager using:
[Azure Key Vault](https://docs.open-metadata.org/v1.3.x/deployment/secrets-manager/supported-implementations/azure-key-vault) but the chart schema validation does not support it. 

### Chart Version

1.3.1

### App Version

1.3.1

### Kubernetes Version

n/a

### Helm Version

n/a

### Relevant Logs

```shell
Error: values don't meet the specifications of the schema(s) in the following chart(s):
openmetadata:
- openmetadata.config.secretsManager: Additional property parameters is not allowed
- openmetadata.config.secretsManager.provider: openmetadata.config.secretsManager.provider must be one of the following: "db", "aws", "aws-ssm", "managed-aws", "managed-aws-ssm", "in-memory"
```

### Custom Helm Values

```yaml
openmetadata:
  config:
    secretsManager:
      provider: managed-azure-kv # or env var SECRET_MANAGER. For non-managed use 'azure-kv'.
      parameters:
        clientId: 
        clientSecret:
          secretRef: 
          secretKey: 
        tenantId: 
        vaultName:
```

### Have you joined Openmetadata Slack community?

Yes

**Comment by Nemeczek** [comment]
@akash-jain-10 hey I think there might be bug:

https://github.com/open-metadata/OpenMetadata/blob/dc4c4e41b8e076d021af77fdd6e98b877944e7af/openmetadata-docs/content/v1.3.x/deployment/secrets-manager/supported-implementations/azure-key-vault/index.md?plain=1#L39

this says:

```
secretsManagerConfiguration:
    secretsManager: managed-azure-kv  # or env var SECRET_MANAGER. For non-managed use 'azure-kv'.
    prefix: ${SECRET_MANAGER_PREFIX:-""} # Define the secret key ID as <prefix>-<clusterName>-<key>
    tags: ${SECRET_MANAGER_TAGS:-[]} # Add tags to the created resource. Format is `[key1:value1,key2:value2,...]`
    parameters:
      clientId: ${OM_SM_CLIENT_ID:-""}
      clientSecret: ${OM_SM_CLIENT_SECRET:-""}
      tenantId: ${OM_SM_TENANT_ID:-""}
      vaultName: ${OM_SM_VAULT_NAME:-""}
```

where the chart itself:
![image](https://github.com/open-metadata/openmetadata-helm-charts/assets/1111404/54955380-117c-4523-9325-304525db4fda)

So I am facing right not:

`org.openmetadata.service.exception.SecretsManagerException: Using Azure Secrets Manager we found a missing or empty `vaultName` parameter. Review your configuration.`

But the chart won't let me to use parameters instead additionalParameters:
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
openmetadata:
- openmetadata.config.secretsManager: Additional property parameters is not allowed
```

**Comment by akash-jain-10** [comment]
Hello @Nemeczek . The Helm Chart expects vaultName as a secret! Make sure to pass it that way!
![image](https://github.com/open-metadata/openmetadata-helm-charts/assets/15995028/e95a24ab-c09a-44ec-a0ce-cb5eb9b78179)

**Comment by Nemeczek** [comment]
Well I do:

```
openmetadata:
  config:
    logLevel: DEBUG
    secretsManager:
      enabled: true
      provider: managed-azure-kv # or env var SECRET_MANAGER. For non-managed use 'azure-kv'.
      additionalParameters:
        vaultName:
          secretRef: secret
          secretKey: openmetadata-secret-manager-key-vault-name
```

**Comment by Nemeczek** [comment]
If I do:
```
openmetadata:
  config:
    logLevel: DEBUG
    secretsManager:
      enabled: true
      provider: managed-azure-kv # or env var SECRET_MANAGER. For non-managed use 'azure-kv'.
      additionalParameters:
        enabled: true #this is needed
        vaultName:
          secretRef: secret
          secretKey: openmetadata-secret-manager-key-vault-name
```

Then It actually reacts to additionalProperties but it generates too mucgh secrets:
![image](https://github.com/open-metadata/openmetadata-helm-charts/assets/1111404/c85731e8-5ca4-4344-9f90-53770654f940)

I think the issue is is in the logic of generation secrets:
https://github.com/open-metadata/openmetadata-helm-charts/blob/83b837ddc66d08ad75252f7b1ba18be665ef152c/charts/openmetadata/templates/secrets.yaml#L152
