### ISSUE TITLE
Helm Chart Indentation issue when using `envFrom` values

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/openmetadata-helm-charts#227]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

Helm chart is not rendering because adding `envFrom` in the helm chart values adds the secret with a wrong indent.

```yaml
envFrom:
    ...
    - secretRef:
       name: openmetadata-fernetkey-secret
  - secretRef:
     name: my-custom-secret
```

### Steps to reproduce

Update helm values to include `envFrom`.

### Chart Version

1.3.1

### App Version

1.3.1

### Kubernetes Version

N/A

### Helm Version

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}

### Relevant Logs

```shell
N/A
```

### Custom Helm Values

```yaml
N/A
```

### Have you joined Openmetadata Slack community?

Yes
