### ISSUE TITLE
OIDC_CUSTOM_PARAMS helm chart default value breaking deployment

### ISSUE THREAD

**Issue by mgorsk1** [open-metadata/openmetadata-helm-charts#229]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

When configuring OM deployment to use new OIDC approach, by default oidcConfiguration.customParams is equal to `""`, which causes failing deployment (migration db init container fails)

### Steps to reproduce

Set 

```
openmetadata:
  configuration:
      authentication:
        enabled: true
        clientType: confidential
        provider: "custom-oidc"
        oidcConfiguration:
          enabled: true
```

and leave `customParams: ""` in values.yaml

deploy.

What fixes this is setting customParams to any proper dictionary, like {"a": "b"} and removing `| quote` wrapper around this parameter.

### Chart Version

1.3.2

### App Version

1.3.2

### Kubernetes Version

n/a

### Helm Version

n/a

### Relevant Logs

```shell
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String ("") to element of `java.util.LinkedHashMap` (but could if coercion was enabled using `CoercionConfig`)
at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.openmetadata.service.OpenMetadataApplicationConfig["authenticationConfiguration"]->org.openmetadata.schema.api.security.AuthenticationConfiguration["oidcConfiguration"]->org.openmetadata.schema.security.client.OidcClientConfig["customParams"])
```

### Custom Helm Values

```yaml
openmetadata:
  configuration:
      authentication:
        enabled: true
        clientType: confidential
        provider: "custom-oidc"
        oidcConfiguration:
          enabled: true
```

### Have you joined Openmetadata Slack community?

Yes

**Comment by jasonstitt** [comment]
The workaround isn't working for me:

```
          customParams: '{"a": "b"}'
```

```
Migrating the OpenMetadata Schema.
Failed to db migration due to
io.dropwizard.configuration.ConfigurationParsingException: /opt/openmetadata/bootstrap/../conf/openmetadata.yaml has an error:
  * Failed to parse configuration at: authenticationConfiguration.oidcConfiguration.customParams; Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"a": "b"}')
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.openmetadata.service.OpenMetadataApplicationConfig["authenticationConfiguration"]->org.openmetadata.schema.api.security.AuthenticationConfiguration["oidcConfiguration"]->org.openmetadata.schema.security.client.OidcClientConfig["customParams"])
```

The chart validates this value as a string so this appears to be the only way to try this workaround?

**Comment by mgorsk1** [comment]
yeah I also had to remove quotes wrapping it, so in the secret there is `{"a": "b"}` instead of `'{"a": "b"}'`

**Comment by mgorsk1** [comment]
- values.yaml
```
openmetadata:
  config:
    authentication:
      oidcConfiguration:
        customParams: '{"a": "b"}'
```
- secrets.yaml
`OIDC_CUSTOM_PARAMS: {{ .oidcConfiguration.customParams | b64enc }}`
