### ISSUE TITLE
I can't use serviceAccount with aws role in annotations

### ISSUE THREAD

**Issue by ivan-yaromka** [open-metadata/openmetadata-helm-charts#232]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

I have one question about EKS deployment.
I installed openmetadata in my eks cluster.
I also enabled serviceAccount in openmetadata values and added annotation to use aws role.
AWS role configured properly, so that openmetadata pod is able to connect to aws using this aws role.
But when i’m trying to add some databases (for example Athena), it says that it doesn’t has enough permissions:
```
(pyathena.error.DatabaseError) An error occurred (AccessDeniedException) when calling the StartQueryExecution operation: You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again.
[SQL: /* {"app": "OpenMetadata", "version": "1.3.2.0"} */
SELECT 42]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```

i didn’t configure AWS Access Key ID and AWS Secret Access Key, because i want to use aws role instead.
Only parameters i filled are:
region
S3 Staging Directory
Athena Workgroup

But it doesn’t work for some reason.
So the question is - can i use aws role in openmetadata instead of AWS Access Key ID and AWS Secret Access Key? Or it’s only one way to connect to aws resources in openmetadata?

### Chart Version

1.3.2

### App Version

1.3.2

### Kubernetes Version

1.27

### Helm Version

3

### Custom Helm Values

```yaml
openmetadata:
            config:
              database:
                auth:
                  password:
                    secretRef: openmetadata-secrets
                    secretKey: openmetadata-mysql-password
                host: openmetadata-cluster.cluster-bla.us-east-1.rds.amazonaws.com
                port: 3306
                driverClass: com.mysql.cj.jdbc.Driver
                dbScheme: mysql
                dbParams: "allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC"
                databaseName: openmetadata
              pipelineServiceClientConfig:
                enabled: true
                # endpoint url for airflow
                apiEndpoint: http://prod-openmetadata-web.bla.svc.cluster.local:8080
                auth:
                  username: admin
                  password:
                    secretRef: openmetadata-secrets
                    secretKey: openmetadata-airflow-password
              elasticsearch:
                host: prod-openmetadata.dns.name
                searchType: opensearch
                port: 443
                scheme: https
                connectionTimeoutSecs: 5
                socketTimeoutSecs: 60
                keepAliveTimeoutSecs: 600
                batchSize: 10
                auth:
                  enabled: true
                  username: openmetadata
                  password:
                    secretRef: openmetadata-secrets
                    secretKey: openmetadata-elasticsearch-password
          nodeSelector: 
            provisioner: bla
            kubernetes.io/arch: amd64
          resources:
            requests:
              cpu: 2
              memory: 2Gi
            limits:
              cpu: 2
              memory: 2Gi
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: alb
              alb.ingress.kubernetes.io/scheme: internal
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
              alb.ingress.kubernetes.io/ssl-redirect: '443'
              alb.ingress.kubernetes.io/group.name: "bla"
              alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS13-1-2-Ext2-2021-06"
            hosts:
              - host: "open-metadata.dns"
                paths:
                  - path: /
                    pathType: Prefix
          serviceAccount:
            create: true
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::account_id:role/EKS-PROD-BI-OPENMETADATA
```

### Have you joined Openmetadata Slack community?

Yes
