### ISSUE TITLE
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)'

### ISSUE THREAD

**Issue by andreyolv** [open-metadata/openmetadata-helm-charts#236]
### Checks

- [X] I have checked for existing issues.
- [ ] This report is about the Openmetadata Helm Chart.
- [X] This report is about the Openmetadata Dependencies Helm Chart.

### Description

Getting started from documentation doesn't work
https://docs.open-metadata.org/v1.3.x/quick-start/local-kubernetes-deployment

mysql pod doesn't run.
kubectl describe pod mysql-0

```
Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Normal   Scheduled  3m39s  default-scheduler  Successfully assigned openmetadata/mysql-0 to k8s-platform-worker3
  Normal   Pulling    3m39s  kubelet            Pulling image "docker.io/bitnami/mysql:8.0.33-debian-11-r0"
  Normal   Pulled     3m37s  kubelet            Successfully pulled image "docker.io/bitnami/mysql:8.0.33-debian-11-r0" in 2.075134746s (2.075143689s including waiting)
  Normal   Created    3m37s  kubelet            Created container mysql
  Normal   Started    3m36s  kubelet            Started container mysql
  Warning  Unhealthy  9s     kubelet            Startup probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!
```

### Steps to reproduce

Follow docs

### Chart Version

1.3.3

### App Version

1.3.3

### Kubernetes Version

1.26.3

### Helm Version

v3.11.3

### Relevant Logs

```shell
Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Normal   Scheduled  3m39s  default-scheduler  Successfully assigned openmetadata/mysql-0 to k8s-platform-worker3
  Normal   Pulling    3m39s  kubelet            Pulling image "docker.io/bitnami/mysql:8.0.33-debian-11-r0"
  Normal   Pulled     3m37s  kubelet            Successfully pulled image "docker.io/bitnami/mysql:8.0.33-debian-11-r0" in 2.075134746s (2.075143689s including waiting)
  Normal   Created    3m37s  kubelet            Created container mysql
  Normal   Started    3m36s  kubelet            Started container mysql
  Warning  Unhealthy  9s     kubelet            Startup probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!
```
```


### Custom Helm Values

```yaml
mysql:
      primary:
        persistence:
          size: 1Gi
    opensearch:
      persistence: 
        size: 1Gi
    airflow:
      dags:
        persistence:
          enabled: false
      logs:
        persistence:
          enabled: false
```

### Have you joined Openmetadata Slack community?

No

**Comment by akash-jain-10** [comment]
Hello @andreyolv  - You might want to check this with Bitnami folks [here](https://github.com/bitnami/charts/tree/main/bitnami/mysql). This does not seem to be related to OpenMetadata. Our Dependencies Helm Chart relies on bitnami MySQL helm charts. Closing this issue here! Thanks.

**Comment by andreyolv** [comment]
this values.yaml solved it:

```
    mysql:
      primary:
        persistence:
          size: 1Gi
        startupProbe:
          enabled: true
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 15
          successThreshold: 1
```
