### ISSUE TITLE
openmetadata uri for alerts integration doesn't work

### ISSUE THREAD

**Issue by dongsupkim-onepredict** [open-metadata/openmetadata-helm-charts#286]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [X] This report is about the Openmetadata Dependencies Helm Chart.

### Description

I have configured OpenMetadata to send alerts via a Slack hook when there are changes in the table schema. However, in the Slack message, the table URI for schema changes still uses the default OpenMetadata URI (`localhost`). I tried updating it to use the internal domain address in the Helm values, but it doesn't seem to be applied. In the OpenMetadata Config Chart Values, it appears that the configuration should be set using `openmetadata.config.openmetadata.host` and `port`, but it seems the values are not being reflected.

```
openmetadata:
  config:
    upgradeMigrationConfigs:
      debug: false
      # You can pass the additional argument flags to the openmetadata-ops.sh migrate command
      # Example if you want to force migration runs, use additionalArgs: "--force"
      additionalArgs: ""
    # Values can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL
    logLevel: INFO
    clusterName: openmetadata
    openmetadata:
      host: "0.0.0.0"
      # URI to use with OpenMetadata Alerts Integrations
      uri: "http://openmetadata:8585" ## This doesn't work
```

### Chart Version

1.5.13

### App Version

1.5.13

### Kubernetes Version

{Version:"1.28.2"}

### Helm Version

{Version:"v3.14.2"}

### Custom Helm Values

```yaml
openmetadata:
  config:
    upgradeMigrationConfigs:
      debug: false
      # You can pass the additional argument flags to the openmetadata-ops.sh migrate command
      # Example if you want to force migration runs, use additionalArgs: "--force"
      # additionalArgs: "--force"
    logLevel: DEBUG
    openmetadata:
      # URI to use with OpenMetadata Alerts Integrations
      uri: "https://openmetadata.onepredict.net"
```

### Have you joined Openmetadata Slack community?

Yes
