### ISSUE TITLE
OpenMetadata Lists not being converted to comma separated ENV values

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/openmetadata-helm-charts#43]
Example - 

List value:
```yaml
global:
  authorizer:
    initialAdmins:
    - "abc"
    - "def"
```
**Expected ENV value** - `'[abc,def]'`
**ENV Value currently generated** - `'[abc def]'`
