### ISSUE TITLE
Customised MySQL does not work in helm install

### ISSUE THREAD

**Issue by lihan** [open-metadata/openmetadata-helm-charts#8]
In my production deployment, I used external MySQL, not from helm dependency. And I have override the `openmetadata.yaml` file to reflect that change.

However in [openmetadata-start.sh](https://github.com/open-metadata/OpenMetadata/blob/main/docker/metadata/openmetadata-start.sh#L13)

`while ! wget -O /dev/null -o /dev/null mysql:3306; do sleep 5; done`

It's assuming mysql is the URI for mysql host. It would not work if MySQL is customised to other url.

As a walk around, I did the following hack in the K8S spec. This would skip the MySQL check and start the server.

```
- name: openmetadata
   image: "openmetadata/server:0.7.0"
   args:
     - "/openmetadata-0.7.0/bin/openmetadata-server-start.sh"
     - "/openmetadata-0.7.0/conf/openmetadata.yaml"
   
```
